### PR TITLE
Added Ollama to run local models

### PR DESCRIPTION
**Pull request by kabe2007**
Enables Ollama to run local models (llama2, codellama, wizard, etc.). Check 'https://ollama.ai/'.

To use, set OLLAMA_HOST to ollama (usually http://localhost:11434), and can then run most of the installed models (they should be defined in ai-models.ts).

### CODE REVIEW

**Comment by navyfighter12** [comment]
> Enables Ollama to run local models (llama2, codellama, wizard, etc.). Check 'https://ollama.ai/'.
> 
> To use, set OLLAMA_HOST to ollama (usually http://localhost:11434), and can then run most of the installed models (they should be defined in ai-models.ts).

I tried to build this new pull request and run in docker but I am getting this error 
Error fetching Ollama models TypeError: fetch failed
Error fetching Ollama models TypeError: fetch failed

I have set OLLAMA_HOST=http://localhost:11434 and also tried 127.0.0.1:11434
Ollama is running
$ ollama serve
2023/10/24 16:24:23 images.go:822: total blobs: 0
2023/10/24 16:24:23 images.go:829: total unused blobs removed: 0
2023/10/24 16:24:23 routes.go:662: Listening on 127.0.0.1:11434 (version 0.1.4)

**Comment by navyfighter12** [comment]
I ran it locally and the error message is gone but not seeing the Ollama models in the UI.

**Comment by kabe2007** [comment]
> > Enables Ollama to run local models (llama2, codellama, wizard, etc.). Check 'https://ollama.ai/'.
> > To use, set OLLAMA_HOST to ollama (usually http://localhost:11434), and can then run most of the installed models (they should be defined in ai-models.ts).
> 
> I tried to build this new pull request and run in docker but I am getting this error Error fetching Ollama models TypeError: fetch failed Error fetching Ollama models TypeError: fetch failed
> 
> I have set OLLAMA_HOST=http://localhost:11434 and also tried 127.0.0.1:11434 Ollama is running $ ollama serve 2023/10/24 16:24:23 images.go:822: total blobs: 0 2023/10/24 16:24:23 images.go:829: total unused blobs removed: 0 2023/10/24 16:24:23 routes.go:662: Listening on 127.0.0.1:11434 (version 0.1.4)

Ensure 3 things: 
1) that you can reach ollama (try wget http://xxx:11434 from inside docker or your unSaged server). ollama is quite picky, may need to set env variables to access from outside (OLLAMA_HOST and OLLAMA_ORIGIN, check https://github.com/jmorganca/ollama/blob/main/docs/faq.md)
2) check firewalls if you cannot reach it
3) re-build

Good luck

**Comment by navyfighter12** [comment]
> > > Enables Ollama to run local models (llama2, codellama, wizard, etc.). Check 'https://ollama.ai/'.
> > > To use, set OLLAMA_HOST to ollama (usually http://localhost:11434), and can then run most of the installed models (they should be defined in ai-models.ts).
> > 
> > 
> > I tried to build this new pull request and run in docker but I am getting this error Error fetching Ollama models TypeError: fetch failed Error fetching Ollama models TypeError: fetch failed
> > I have set OLLAMA_HOST=http://localhost:11434 and also tried 127.0.0.1:11434 Ollama is running $ ollama serve 2023/10/24 16:24:23 images.go:822: total blobs: 0 2023/10/24 16:24:23 images.go:829: total unused blobs removed: 0 2023/10/24 16:24:23 routes.go:662: Listening on 127.0.0.1:11434 (version 0.1.4)
> 
> Ensure 3 things:
> 
> 1. that you can reach ollama (try wget http://xxx:11434 from inside docker or your unSaged server). ollama is quite picky, may need to set env variables to access from outside (OLLAMA_HOST and OLLAMA_ORIGIN, check https://github.com/jmorganca/ollama/blob/main/docs/faq.md)
> 2. check firewalls if you cannot reach it
> 3. re-build
> 
> Good luck

I tried locally but I get this error. I will try on my main pc later tonight

Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'id')

Source
components/Home/components/SecondaryMenu/components/Menu/components/Screens/ModelSettings/components/ModelSelect.tsx (41:25) @ id

  39 | <option
  40 |   key={model.id}
> 41 |   value={model.id}
     |               ^
  42 |   className="bg-theme-primary-menu-light dark:bg-theme-primary-menu-dark text-black dark:text-white"
  43 | >
  44 |   {model.id}
Call Stack
map
components/Home/components/SecondaryMenu/components/Menu/components/Screens/ModelSettings/components/ModelSelect.tsx (38:16)
Show collapsed frames

**Comment by navyfighter12** [comment]
Made a little progress. Was able to run the curl command and access Ollama via the docker container ip but still not working with unSAGED. I will keep troubleshooting

**Comment by navyfighter12** [comment]
> > > Enables Ollama to run local models (llama2, codellama, wizard, etc.). Check 'https://ollama.ai/'.
> > > To use, set OLLAMA_HOST to ollama (usually http://localhost:11434), and can then run most of the installed models (they should be defined in ai-models.ts).
> > 
> > 
> > I tried to build this new pull request and run in docker but I am getting this error Error fetching Ollama models TypeError: fetch failed Error fetching Ollama models TypeError: fetch failed
> > I have set OLLAMA_HOST=http://localhost:11434 and also tried 127.0.0.1:11434 Ollama is running $ ollama serve 2023/10/24 16:24:23 images.go:822: total blobs: 0 2023/10/24 16:24:23 images.go:829: total unused blobs removed: 0 2023/10/24 16:24:23 routes.go:662: Listening on 127.0.0.1:11434 (version 0.1.4)
> 
> Ensure 3 things:
> 
> 1. that you can reach ollama (try wget http://xxx:11434 from inside docker or your unSaged server). ollama is quite picky, may need to set env variables to access from outside (OLLAMA_HOST and OLLAMA_ORIGIN, check https://github.com/jmorganca/ollama/blob/main/docs/faq.md)
> 2. check firewalls if you cannot reach it
> 3. re-build
> 
> Good luck



> > > Enables Ollama to run local models (llama2, codellama, wizard, etc.). Check 'https://ollama.ai/'.
> > > To use, set OLLAMA_HOST to ollama (usually http://localhost:11434), and can then run most of the installed models (they should be defined in ai-models.ts).
> > 
> > 
> > I tried to build this new pull request and run in docker but I am getting this error Error fetching Ollama models TypeError: fetch failed Error fetching Ollama models TypeError: fetch failed
> > I have set OLLAMA_HOST=http://localhost:11434 and also tried 127.0.0.1:11434 Ollama is running $ ollama serve 2023/10/24 16:24:23 images.go:822: total blobs: 0 2023/10/24 16:24:23 images.go:829: total unused blobs removed: 0 2023/10/24 16:24:23 routes.go:662: Listening on 127.0.0.1:11434 (version 0.1.4)
> 
> Ensure 3 things:
> 
> 1. that you can reach ollama (try wget http://xxx:11434 from inside docker or your unSaged server). ollama is quite picky, may need to set env variables to access from outside (OLLAMA_HOST and OLLAMA_ORIGIN, check https://github.com/jmorganca/ollama/blob/main/docs/faq.md)
> 2. check firewalls if you cannot reach it
> 3. re-build
> 
> Good luck

okay well i was able to test the curl line inside the unSAGED docker and access the Ollama docker so now I see the models in the web interface and use them. 

Thanks again for the help

**Comment by navyfighter12** [comment]
Not a major issue but maybe for others is if they download one of the models thats not in the ai model list for unSAGED the web interface breaks. Easiest solution is to add all of them but that is  a bit time consuming.

**Comment by kabe2007** [comment]
> Not a major issue but maybe for others is if they download one of the models thats not in the ai model list for unSAGED the web interface breaks. Easiest solution is to add all of them but that is a bit time consuming.

You are correct, pushing now a fix

**Review by jorge-menjivar — APPROVED** [review]

**Pull request merged**
