### PR TITLE
[WIP] Desktop applications

### PR DESCRIPTION
**Pull request by jorge-menjivar**
Work in progress. This pull request has the code for building Windows, macOS, and Linux applications. This will become a separate app in the monorepo, although this app also contains many updates that will also be merged into the web app.

The following are the things that will differentiate the desktop app:
- No server-side code
- API keys are stored in OS keyring/keychain
- Token count runs over Rust rather than TypeScript
- All streaming functions are rewritten in Rust to overcome CORS limitations in the browser.
- Ollama model fetcher was also rewritten in Rust to overcome CORS issue.

Progress:
- [X] Implement support for local storage
- [X] Save API keys to OS keyring
- [X] Change Ollama completion stream so it works locally
- [X] Change OpenAI completion stream so it works locally
- [x] Change Anthropic completion stream so it works locally
- [x] Change PaLM completion steam so it works locally
- [ ] Merge #105 to enable authentication without a server
- [ ] Re-implement support for supabase storage, but with supabase auth
- [x] Github workflow to automatically produce Linux release
- [x] Github workflow to automatically produce MacOS release
- [x] Github workflow to automatically produce Windows release

Instructions to run desktop app:
1. Make sure that you have all of Tauri's prerequisites: https://tauri.app/v1/guides/getting-started/prerequisites/
2. `pnpm install`
3. `cd apps/desktop`
4. `pnpm tauri dev`
 
## Optional
You shouldn't have to do this for ollama to work, but I'm leaving this just in case.
To access ollama models you must set the env variable `OLLAMA_ORIGINS=*://localhost` for the ollama service.

Their documentation is not very clear, so here's my guide:

### Linux
1. Add the following content to `/etc/systemd/system/ollama.service.d/environment.conf`. You may need to create the file and directory.
    ```toml
    [Service]
    Environment="OLLAMA_ORIGINS=*://localhost"
    ```

2. Run
    ```sh
    sudo systemctl daemon-reload
    sudo systemctl restart ollama
    ```

### macOS
1. Run `OLLAMA_ORIGINS=*://localhost ollama serve`

[Ollama documentation source](https://github.com/jmorganca/ollama/blob/main/docs/faq.md)

### CODE REVIEW

**Comment by sebiweise** [comment]
I think we should create a new directory for your changes so our monorepo structure will look like this:
apps
    docs
    desktop
    web
packages
   eslint-config-custom
   tsconfig
   shared-code (coming later)

**Comment by Bortus-AI** [comment]
> I think we should create a new directory for your changes so our monorepo structure will look like this: apps docs desktop web
> 
> packages eslint-config-custom tsconfig shared-code (coming later)

Good idea!

**Comment by jorge-menjivar** [comment]
The streaming functions and ollama model fetcher are now rusty. Running outside the browser environment allows us to skip CORS checks by the browser.

**Comment by jorge-menjivar** [comment]
Closing this in favor of #165 to make it easier to merge

**Pull request closed without merging**
