### PR TITLE
Move from next-auth to supabase-auth - WIP

### PR DESCRIPTION
**Pull request by daniel-farina**
This PR moves this project away from next-auth to supabase-auth. This makes the configuration a lot simpler. 

Tasks:

- [x] removed next-auth references and libraries
- [x] updated db migration
- [x] update .env sample
- [x] update docs (might need more revisions)
- [x] add login/logout
- [x] add google enabled by default
- [x] refactored helper

Now the application works immediately once supabase is configured, you can login with magic links, no need to setup smtp providers. 

# Todo
The login by *@email feature has been removed, we might want to add that again

###  Upgrading
This PR works on a brand new installation only, We might need to add a migration script to migrate users form next-auth to supabase-auth.  The auth table is already available by default in supabase, I think it would just be a matter of moving users from next-auth table to auth table and then updating all the db changes seen here: https://github.com/jorge-menjivar/unSAGED/pull/97/files#diff-8afbaed08ea2245ce9c16b9011699a8f683c2618a6f1d4e88d243028204a4aa5 another option is to export all data,  run the application from scratch then import data back.

### CODE REVIEW

**Comment by sebiweise** [comment]
Hi Daniel, you can have a look at PR #95 I´ve done some updates that can be adopted in your WIP.
Maybe it would be possible to implement supabase-auth and Clerk for the users who want to use Clerk?

**Comment by daniel-farina** [comment]
> Hi Daniel, you can have a look at PR #95 I´ve done some updates that can be adopted in your WIP. Maybe it would be possible to implement supabase-auth and Clerk for the users who want to use Clerk?

Amazing, doing supabase auth + Clerk would be the best outcome.  What do you think would be the best way to merge both? Maybe cherry pick your Clerk changes and add them as a separate PR to make sure we have clear history of:
- adding supabase-auth
- adding Clerk

Clerk should be conditional where a user can select supabase or clerk via an environment variable.  I could probably look into this. 


Looking at your PR it has a ton of changes. I think it would be a lot better to break them down into parts:
-AI model changes
-Clerk Support
-Turbo refactoring

Else it becomes a little difficult to merge, thoughts?

**Comment by sebiweise** [comment]
> > Hi Daniel, you can have a look at PR #95 I´ve done some updates that can be adopted in your WIP. Maybe it would be possible to implement supabase-auth and Clerk for the users who want to use Clerk?
> 
> Amazing, doing supabase auth + Clerk would be the best outcome. What do you think would be the best way to merge both? Maybe cherry pick your Clerk changes and add them as a separate PR to make sure we have clear history of:
> 
> * adding supabase-auth
> * adding Clerk
> 
> Clerk should be conditional where a user can select supabase or clerk via an environment variable. I could probably look into this.
> 
> Looking at your PR it has a ton of changes. I think it would be a lot better to break them down into parts: -AI model changes -Clerk Support -Turbo refactoring
> 
> Else it becomes a little difficult to merge, thoughts?

I just reverted my clerk changes, I will just push my clerk_auth branch to this repo so you can have a look at the changes I´ve made, maybe it is helpful for the future changes.

**Comment by jorge-menjivar** [comment]
I will merge #99 in for now so that new pull requests start building on top of that since it is a significant change. We will need to update this work so that it is on top of these changes. I will get started on building the desktop app on top of the refactored changes as well.

**Comment by daniel-farina** [comment]
> I will merge #99 in for now so that new pull requests start building on top of that since it is a significant change. We will need to update this work so that it is on top of these changes. I will get started on building the desktop app on top of the refactored changes as well.

sounds good!

**Comment by daniel-farina** [comment]
Closing this in favor of https://github.com/jorge-menjivar/unsaged/pull/105

**Pull request closed without merging**
